In [65]:
import pandas as pd
import numpy as np
import matplotlib as pyplot
import seaborn as sns
import joblib
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import TimeSeriesSplit
import warnings
warnings.filterwarnings('ignore')

In [13]:
df=pd.read_csv('city_day.csv')

In [14]:
df['City'].unique()

<StringArray>
[         'Ahmedabad',             'Aizawl',          'Amaravati',
           'Amritsar',          'Bengaluru',             'Bhopal',
       'Brajrajnagar',         'Chandigarh',            'Chennai',
         'Coimbatore',              'Delhi',          'Ernakulam',
           'Gurugram',           'Guwahati',          'Hyderabad',
             'Jaipur',         'Jorapokhar',              'Kochi',
            'Kolkata',            'Lucknow',             'Mumbai',
              'Patna',           'Shillong',            'Talcher',
 'Thiruvananthapuram',      'Visakhapatnam']
Length: 26, dtype: str

In [15]:
len(df.columns)

16

In [16]:
print(f"PM10 Null values:",{(df['PM10'].isnull().sum()/len(df))*100})
print(f"PM2.5 Null values:",{(df['PM2.5'].isnull().sum()/len(df))*100})
print(f"NO Null values:",{(df['NO'].isnull().sum()/len(df))*100})
print(f"NO2 Null values:",{(df['NO2'].isnull().sum()/len(df))*100})
print(f"NOx Null values:",{(df['NOx'].isnull().sum()/len(df))*100})
print(f"NH3 Null values:",{(df['NH3'].isnull().sum()/len(df))*100})
print(f"CO Null values:",{(df['CO'].isnull().sum()/len(df))*100})
print(f"SO2 Null values:",{(df['SO2'].isnull().sum()/len(df))*100})
print(f"O3 Null values:",{(df['O3'].isnull().sum()/len(df))*100})
print(f"Benzene Null values:",{(df['Benzene'].isnull().sum()/len(df))*100})
print(f"Toluene Null values:",{(df['Toluene'].isnull().sum()/len(df))*100})
print(f"xylene Null values:",{(df['Xylene'].isnull().sum()/len(df))*100})

PM10 Null values: {np.float64(37.72307067149775)}
PM2.5 Null values: {np.float64(15.570078900138837)}
NO Null values: {np.float64(12.129626494192543)}
NO2 Null values: {np.float64(12.139785310351833)}
NOx Null values: {np.float64(14.17154854220988)}
NH3 Null values: {np.float64(34.97341776438319)}
CO Null values: {np.float64(6.9723341573262)}
SO2 Null values: {np.float64(13.050692492634857)}
O3 Null values: {np.float64(13.619586197555112)}
Benzene Null values: {np.float64(19.041007754563)}
Toluene Null values: {np.float64(27.229013578950934)}
xylene Null values: {np.float64(61.32200060952897)}

In [17]:
df.groupby('City').count().head()

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,2009,1381,407,1400,1401,1415,0,1400,1369,1324,1526,1526,1525,1334,1334
Aizawl,113,111,112,113,113,113,113,113,113,104,98,98,0,111,111
Amaravati,951,892,896,896,896,896,896,854,886,896,876,876,682,841,841
Amritsar,1221,1093,1158,1128,1177,932,1179,1145,1053,1106,1026,1009,1008,1126,1126
Bengaluru,2009,1863,1649,2003,2003,2005,1806,1998,2003,1865,1743,1916,0,1910,1910

In [18]:
x=df.groupby('City')['PM10'].mean()
print(x)

City
Ahmedabad             114.584029
Aizawl                 23.352857
Amaravati              76.362020
Amritsar              115.202599
Bengaluru              83.243287
Bhopal                119.324321
Brajrajnagar          124.217373
Chandigarh             85.656546
Chennai                62.834404
Coimbatore             37.982137
Delhi                 232.809229
Ernakulam              48.335633
Gurugram              191.504432
Guwahati              116.604900
Hyderabad              91.931532
Jaipur                123.483509
Jorapokhar            149.657942
Kochi                  67.335432
Kolkata               115.629499
Lucknow                      NaN
Mumbai                 96.745059
Patna                 126.747958
Shillong               42.199170
Talcher               165.772708
Thiruvananthapuram     52.863659
Visakhapatnam         105.951354
Name: PM10, dtype: float64

In [19]:
df["PM10"] = df.groupby("City")["PM10"].transform(
    lambda x: x.fillna(x.median())
)

In [20]:
df['PM10'].isnull().sum()

np.int64(2009)

In [21]:
df[df["City"] == "Lucknow"].isnull().sum()

City             0
Date             0
PM2.5          102
PM10          2009
NO              24
NO2             24
NOx            324
NH3           1004
CO              28
SO2             64
O3              27
Benzene         99
Toluene        136
Xylene        2009
AQI            116
AQI_Bucket     116
dtype: int64

In [22]:
df.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10           2009
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [23]:
df.groupby("City")["PM10"].apply(lambda x: x.isnull().sum())

City
Ahmedabad                0
Aizawl                   0
Amaravati                0
Amritsar                 0
Bengaluru                0
Bhopal                   0
Brajrajnagar             0
Chandigarh               0
Chennai                  0
Coimbatore               0
Delhi                    0
Ernakulam                0
Gurugram                 0
Guwahati                 0
Hyderabad                0
Jaipur                   0
Jorapokhar               0
Kochi                    0
Kolkata                  0
Lucknow               2009
Mumbai                   0
Patna                    0
Shillong                 0
Talcher                  0
Thiruvananthapuram       0
Visakhapatnam            0
Name: PM10, dtype: int64

In [24]:
#removing Lucknow data
df = df[df["City"] != "Lucknow"]

In [25]:
df.groupby("City")["PM10"].apply(lambda x: x.isnull().sum())

City
Ahmedabad             0
Aizawl                0
Amaravati             0
Amritsar              0
Bengaluru             0
Bhopal                0
Brajrajnagar          0
Chandigarh            0
Chennai               0
Coimbatore            0
Delhi                 0
Ernakulam             0
Gurugram              0
Guwahati              0
Hyderabad             0
Jaipur                0
Jorapokhar            0
Kochi                 0
Kolkata               0
Mumbai                0
Patna                 0
Shillong              0
Talcher               0
Thiruvananthapuram    0
Visakhapatnam         0
Name: PM10, dtype: int64

In [26]:
df.groupby("City").apply(lambda x: x.isnull().sum())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,0,628,0,609,608,594,2009,609,640,685,483,483,484,675,675
Aizawl,0,2,0,0,0,0,0,0,0,9,15,15,113,2,2
Amaravati,0,59,0,55,55,55,55,97,65,55,75,75,269,110,110
Amritsar,0,128,0,93,44,289,42,76,168,115,195,212,213,95,95
Bengaluru,0,146,0,6,6,4,203,11,6,144,266,93,2009,99,99
Bhopal,0,9,0,9,9,9,9,9,9,9,289,289,289,11,11
Brajrajnagar,0,185,0,243,234,175,226,150,193,203,173,938,938,225,225
Chandigarh,0,15,0,4,4,4,10,0,0,0,0,0,0,5,5
Chennai,0,117,0,36,36,36,462,25,36,49,285,253,2009,125,125
Coimbatore,0,8,0,55,11,4,123,3,3,3,3,3,386,42,42
Delhi,0,2,0,2,2,0,9,0,110,84,0,0,781,10,10
Ernakulam,0,4,0,4,55,4,4,4,4,162,4,4,4,9,9
Gurugram,0,154,0,138,136,452,1560,109,175,116,442,610,1560,226,226
Guwahati,0,1,0,1,1,1,1,1,1,1,7,502,502,7,7
Hyderabad,0,115,0,28,28,7,360,5,26,26,127,127,127,126,126
Jaipur,0,12,0,16,14,112,15,7,12,15,22,23,1114,20,20
Jorapokhar,0,790,0,270,270,1169,368,513,351,294,1169,1169,1169,398,398
Kochi,0,0,0,2,6,0,16,0,0,0,162,0,162,4,4
Kolkata,0,55,0,26,25,1,0,0,62,50,1,1,420,60,60
Mumbai,0,1225,0,1242,1253,499,1614,25,1220,1212,210,993,994,1234,1234
Patna,0,321,0,203,204,203,1667,151,205,278,172,173,172,399,399
Shillong,0,64,0,59,59,33,59,33,54,56,33,34,310,105,105
Talcher,0,184,0,200,222,156,186,148,192,169,241,758,925,227,227
Thiruvananthapuram,0,42,0,31,31,16,113,16,31,31,1112,1112,1112,60,60
Visakhapatnam,0,230,0,226,248,38,213,39,227,229,38,38,38,291,291

In [27]:
df.groupby("City").apply(lambda x: x.count())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,2009,1381,2009,1400,1401,1415,0,1400,1369,1324,1526,1526,1525,1334,1334
Aizawl,113,111,113,113,113,113,113,113,113,104,98,98,0,111,111
Amaravati,951,892,951,896,896,896,896,854,886,896,876,876,682,841,841
Amritsar,1221,1093,1221,1128,1177,932,1179,1145,1053,1106,1026,1009,1008,1126,1126
Bengaluru,2009,1863,2009,2003,2003,2005,1806,1998,2003,1865,1743,1916,0,1910,1910
Bhopal,289,280,289,280,280,280,280,280,280,280,0,0,0,278,278
Brajrajnagar,938,753,938,695,704,763,712,788,745,735,765,0,0,713,713
Chandigarh,304,289,304,300,300,300,294,304,304,304,304,304,304,299,299
Chennai,2009,1892,2009,1973,1973,1973,1547,1984,1973,1960,1724,1756,0,1884,1884
Coimbatore,386,378,386,331,375,382,263,383,383,383,383,383,0,344,344
Delhi,2009,2007,2009,2007,2007,2009,2000,2009,1899,1925,2009,2009,1228,1999,1999
Ernakulam,162,158,162,158,107,158,158,158,158,0,158,158,158,153,153
Gurugram,1679,1525,1679,1541,1543,1227,119,1570,1504,1563,1237,1069,119,1453,1453
Guwahati,502,501,502,501,501,501,501,501,501,501,495,0,0,495,495
Hyderabad,2006,1891,2006,1978,1978,1999,1646,2001,1980,1980,1879,1879,1879,1880,1880
Jaipur,1114,1102,1114,1098,1100,1002,1099,1107,1102,1099,1092,1091,0,1094,1094
Jorapokhar,1169,379,1169,899,899,0,801,656,818,875,0,0,0,771,771
Kochi,162,162,162,160,156,162,146,162,162,162,0,162,0,158,158
Kolkata,814,759,814,788,789,813,814,814,752,764,813,813,394,754,754
Mumbai,2009,784,2009,767,756,1510,395,1984,789,797,1799,1016,1015,775,775
Patna,1858,1537,1858,1655,1654,1655,191,1707,1653,1580,1686,1685,1686,1459,1459
Shillong,310,246,310,251,251,277,251,277,256,254,277,276,0,205,205
Talcher,925,741,925,725,703,769,739,777,733,756,684,167,0,698,698
Thiruvananthapuram,1112,1070,1112,1081,1081,1096,999,1096,1081,1081,0,0,0,1052,1052
Visakhapatnam,1462,1232,1462,1236,1214,1424,1249,1423,1235,1233,1424,1424,1424,1171,1171

In [ ]:
df["PM2.5"] = df.groupby("City")["PM2.5"].transform(
    lambda x: x.fillna(x.median())
)
df["PM10"] = df.groupby("City")["PM10"].transform(
    lambda x: x.fillna(x.median())
)
df["NO"] = df.groupby("City")["NO"].transform(
    lambda x: x.fillna(x.median())
)
df["NO2"] = df.groupby("City")["NO2"].transform(
    lambda x: x.fillna(x.median())
)
df["NOx"] = df.groupby("City")["NOx"].transform(
    lambda x: x.fillna(x.median())
)
df["NH3"] = df.groupby("City")["NH3"].transform(
    lambda x: x.fillna(x.median())
)
df["CO"] = df.groupby("City")["CO"].transform(
    lambda x: x.fillna(x.median())
)
df["SO2"] = df.groupby("City")["SO2"].transform(
    lambda x: x.fillna(x.median())
)
df["O3"] = df.groupby("City")["O3"].transform(
    lambda x: x.fillna(x.median())
)

In [29]:
df.groupby("City").apply(lambda x: x.isnull().sum())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,0,0,0,0,0,0,2009,0,0,0,483,483,484,675,675
Aizawl,0,0,0,0,0,0,0,0,0,0,15,15,113,2,2
Amaravati,0,0,0,0,0,0,0,0,0,0,75,75,269,110,110
Amritsar,0,0,0,0,0,0,0,0,0,0,195,212,213,95,95
Bengaluru,0,0,0,0,0,0,0,0,0,0,266,93,2009,99,99
Bhopal,0,0,0,0,0,0,0,0,0,0,289,289,289,11,11
Brajrajnagar,0,0,0,0,0,0,0,0,0,0,173,938,938,225,225
Chandigarh,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5
Chennai,0,0,0,0,0,0,0,0,0,0,285,253,2009,125,125
Coimbatore,0,0,0,0,0,0,0,0,0,0,3,3,386,42,42
Delhi,0,0,0,0,0,0,0,0,0,0,0,0,781,10,10
Ernakulam,0,0,0,0,0,0,0,0,0,162,4,4,4,9,9
Gurugram,0,0,0,0,0,0,0,0,0,0,442,610,1560,226,226
Guwahati,0,0,0,0,0,0,0,0,0,0,7,502,502,7,7
Hyderabad,0,0,0,0,0,0,0,0,0,0,127,127,127,126,126
Jaipur,0,0,0,0,0,0,0,0,0,0,22,23,1114,20,20
Jorapokhar,0,0,0,0,0,1169,0,0,0,0,1169,1169,1169,398,398
Kochi,0,0,0,0,0,0,0,0,0,0,162,0,162,4,4
Kolkata,0,0,0,0,0,0,0,0,0,0,1,1,420,60,60
Mumbai,0,0,0,0,0,0,0,0,0,0,210,993,994,1234,1234
Patna,0,0,0,0,0,0,0,0,0,0,172,173,172,399,399
Shillong,0,0,0,0,0,0,0,0,0,0,33,34,310,105,105
Talcher,0,0,0,0,0,0,0,0,0,0,241,758,925,227,227
Thiruvananthapuram,0,0,0,0,0,0,0,0,0,0,1112,1112,1112,60,60
Visakhapatnam,0,0,0,0,0,0,0,0,0,0,38,38,38,291,291

In [30]:
df.groupby("City").apply(lambda x: x.isnull().sum())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,0,0,0,0,0,0,2009,0,0,0,483,483,484,675,675
Aizawl,0,0,0,0,0,0,0,0,0,0,15,15,113,2,2
Amaravati,0,0,0,0,0,0,0,0,0,0,75,75,269,110,110
Amritsar,0,0,0,0,0,0,0,0,0,0,195,212,213,95,95
Bengaluru,0,0,0,0,0,0,0,0,0,0,266,93,2009,99,99
Bhopal,0,0,0,0,0,0,0,0,0,0,289,289,289,11,11
Brajrajnagar,0,0,0,0,0,0,0,0,0,0,173,938,938,225,225
Chandigarh,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5
Chennai,0,0,0,0,0,0,0,0,0,0,285,253,2009,125,125
Coimbatore,0,0,0,0,0,0,0,0,0,0,3,3,386,42,42
Delhi,0,0,0,0,0,0,0,0,0,0,0,0,781,10,10
Ernakulam,0,0,0,0,0,0,0,0,0,162,4,4,4,9,9
Gurugram,0,0,0,0,0,0,0,0,0,0,442,610,1560,226,226
Guwahati,0,0,0,0,0,0,0,0,0,0,7,502,502,7,7
Hyderabad,0,0,0,0,0,0,0,0,0,0,127,127,127,126,126
Jaipur,0,0,0,0,0,0,0,0,0,0,22,23,1114,20,20
Jorapokhar,0,0,0,0,0,1169,0,0,0,0,1169,1169,1169,398,398
Kochi,0,0,0,0,0,0,0,0,0,0,162,0,162,4,4
Kolkata,0,0,0,0,0,0,0,0,0,0,1,1,420,60,60
Mumbai,0,0,0,0,0,0,0,0,0,0,210,993,994,1234,1234
Patna,0,0,0,0,0,0,0,0,0,0,172,173,172,399,399
Shillong,0,0,0,0,0,0,0,0,0,0,33,34,310,105,105
Talcher,0,0,0,0,0,0,0,0,0,0,241,758,925,227,227
Thiruvananthapuram,0,0,0,0,0,0,0,0,0,0,1112,1112,1112,60,60
Visakhapatnam,0,0,0,0,0,0,0,0,0,0,38,38,38,291,291

In [33]:
#removing Joraphokar data
df = df[df["City"] != "Jorapokhar"]

In [34]:
df.groupby("City").apply(lambda x: x.isnull().sum())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,0,0,0,0,0,0,2009,0,0,0,483,483,484,675,675
Aizawl,0,0,0,0,0,0,0,0,0,0,15,15,113,2,2
Amaravati,0,0,0,0,0,0,0,0,0,0,75,75,269,110,110
Amritsar,0,0,0,0,0,0,0,0,0,0,195,212,213,95,95
Bengaluru,0,0,0,0,0,0,0,0,0,0,266,93,2009,99,99
Bhopal,0,0,0,0,0,0,0,0,0,0,289,289,289,11,11
Brajrajnagar,0,0,0,0,0,0,0,0,0,0,173,938,938,225,225
Chandigarh,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5
Chennai,0,0,0,0,0,0,0,0,0,0,285,253,2009,125,125
Coimbatore,0,0,0,0,0,0,0,0,0,0,3,3,386,42,42
Delhi,0,0,0,0,0,0,0,0,0,0,0,0,781,10,10
Ernakulam,0,0,0,0,0,0,0,0,0,162,4,4,4,9,9
Gurugram,0,0,0,0,0,0,0,0,0,0,442,610,1560,226,226
Guwahati,0,0,0,0,0,0,0,0,0,0,7,502,502,7,7
Hyderabad,0,0,0,0,0,0,0,0,0,0,127,127,127,126,126
Jaipur,0,0,0,0,0,0,0,0,0,0,22,23,1114,20,20
Kochi,0,0,0,0,0,0,0,0,0,0,162,0,162,4,4
Kolkata,0,0,0,0,0,0,0,0,0,0,1,1,420,60,60
Mumbai,0,0,0,0,0,0,0,0,0,0,210,993,994,1234,1234
Patna,0,0,0,0,0,0,0,0,0,0,172,173,172,399,399
Shillong,0,0,0,0,0,0,0,0,0,0,33,34,310,105,105
Talcher,0,0,0,0,0,0,0,0,0,0,241,758,925,227,227
Thiruvananthapuram,0,0,0,0,0,0,0,0,0,0,1112,1112,1112,60,60
Visakhapatnam,0,0,0,0,0,0,0,0,0,0,38,38,38,291,291

In [ ]:
# Median NH3 from similar cities
fill_value = df[df['City'].isin(['Delhi', 'Gurugram', 'Jaipur'])]['NH3'].median()
print(fill_value)

25.045

In [37]:
# Fill Ahmedabad NH3 missing values
df.loc[
    (df['City'] == 'Ahmedabad') & (df['NH3'].isna()),
    'NH3'
] = fill_value

In [41]:
df.groupby("City").apply(lambda x: x.isnull().sum())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,0,0,0,0,0,0,0,0,0,0,483,483,484,675,675
Aizawl,0,0,0,0,0,0,0,0,0,0,15,15,113,2,2
Amaravati,0,0,0,0,0,0,0,0,0,0,75,75,269,110,110
Amritsar,0,0,0,0,0,0,0,0,0,0,195,212,213,95,95
Bengaluru,0,0,0,0,0,0,0,0,0,0,266,93,2009,99,99
Bhopal,0,0,0,0,0,0,0,0,0,0,289,289,289,11,11
Brajrajnagar,0,0,0,0,0,0,0,0,0,0,173,938,938,225,225
Chandigarh,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5
Chennai,0,0,0,0,0,0,0,0,0,0,285,253,2009,125,125
Coimbatore,0,0,0,0,0,0,0,0,0,0,3,3,386,42,42
Delhi,0,0,0,0,0,0,0,0,0,0,0,0,781,10,10
Ernakulam,0,0,0,0,0,0,0,0,0,162,4,4,4,9,9
Gurugram,0,0,0,0,0,0,0,0,0,0,442,610,1560,226,226
Guwahati,0,0,0,0,0,0,0,0,0,0,7,502,502,7,7
Hyderabad,0,0,0,0,0,0,0,0,0,0,127,127,127,126,126
Jaipur,0,0,0,0,0,0,0,0,0,0,22,23,1114,20,20
Kochi,0,0,0,0,0,0,0,0,0,0,162,0,162,4,4
Kolkata,0,0,0,0,0,0,0,0,0,0,1,1,420,60,60
Mumbai,0,0,0,0,0,0,0,0,0,0,210,993,994,1234,1234
Patna,0,0,0,0,0,0,0,0,0,0,172,173,172,399,399
Shillong,0,0,0,0,0,0,0,0,0,0,33,34,310,105,105
Talcher,0,0,0,0,0,0,0,0,0,0,241,758,925,227,227
Thiruvananthapuram,0,0,0,0,0,0,0,0,0,0,1112,1112,1112,60,60
Visakhapatnam,0,0,0,0,0,0,0,0,0,0,38,38,38,291,291

In [42]:
# Kochi O3 median
fill_value = df[df['City'] == 'Kochi']['O3'].median()

# Fill Ernakulam O3 missing values
df.loc[
    (df['City'] == 'Ernakulam') & (df['O3'].isna()),
    'O3'
] = fill_value

In [43]:
df.groupby("City").apply(lambda a: a.isnull().sum())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,0,0,0,0,0,0,0,0,0,0,483,483,484,675,675
Aizawl,0,0,0,0,0,0,0,0,0,0,15,15,113,2,2
Amaravati,0,0,0,0,0,0,0,0,0,0,75,75,269,110,110
Amritsar,0,0,0,0,0,0,0,0,0,0,195,212,213,95,95
Bengaluru,0,0,0,0,0,0,0,0,0,0,266,93,2009,99,99
Bhopal,0,0,0,0,0,0,0,0,0,0,289,289,289,11,11
Brajrajnagar,0,0,0,0,0,0,0,0,0,0,173,938,938,225,225
Chandigarh,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5
Chennai,0,0,0,0,0,0,0,0,0,0,285,253,2009,125,125
Coimbatore,0,0,0,0,0,0,0,0,0,0,3,3,386,42,42
Delhi,0,0,0,0,0,0,0,0,0,0,0,0,781,10,10
Ernakulam,0,0,0,0,0,0,0,0,0,0,4,4,4,9,9
Gurugram,0,0,0,0,0,0,0,0,0,0,442,610,1560,226,226
Guwahati,0,0,0,0,0,0,0,0,0,0,7,502,502,7,7
Hyderabad,0,0,0,0,0,0,0,0,0,0,127,127,127,126,126
Jaipur,0,0,0,0,0,0,0,0,0,0,22,23,1114,20,20
Kochi,0,0,0,0,0,0,0,0,0,0,162,0,162,4,4
Kolkata,0,0,0,0,0,0,0,0,0,0,1,1,420,60,60
Mumbai,0,0,0,0,0,0,0,0,0,0,210,993,994,1234,1234
Patna,0,0,0,0,0,0,0,0,0,0,172,173,172,399,399
Shillong,0,0,0,0,0,0,0,0,0,0,33,34,310,105,105
Talcher,0,0,0,0,0,0,0,0,0,0,241,758,925,227,227
Thiruvananthapuram,0,0,0,0,0,0,0,0,0,0,1112,1112,1112,60,60
Visakhapatnam,0,0,0,0,0,0,0,0,0,0,38,38,38,291,291

In [44]:
df["AQI"] = df.groupby("City")["AQI"].transform(
    lambda x: x.fillna(x.median())
)

In [45]:

df.groupby("City").apply(lambda a: a.isnull().sum())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
City,,,,,,,,,,,,,,,
Ahmedabad,0,0,0,0,0,0,0,0,0,0,483,483,484,0,675
Aizawl,0,0,0,0,0,0,0,0,0,0,15,15,113,0,2
Amaravati,0,0,0,0,0,0,0,0,0,0,75,75,269,0,110
Amritsar,0,0,0,0,0,0,0,0,0,0,195,212,213,0,95
Bengaluru,0,0,0,0,0,0,0,0,0,0,266,93,2009,0,99
Bhopal,0,0,0,0,0,0,0,0,0,0,289,289,289,0,11
Brajrajnagar,0,0,0,0,0,0,0,0,0,0,173,938,938,0,225
Chandigarh,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5
Chennai,0,0,0,0,0,0,0,0,0,0,285,253,2009,0,125
Coimbatore,0,0,0,0,0,0,0,0,0,0,3,3,386,0,42
Delhi,0,0,0,0,0,0,0,0,0,0,0,0,781,0,10
Ernakulam,0,0,0,0,0,0,0,0,0,0,4,4,4,0,9
Gurugram,0,0,0,0,0,0,0,0,0,0,442,610,1560,0,226
Guwahati,0,0,0,0,0,0,0,0,0,0,7,502,502,0,7
Hyderabad,0,0,0,0,0,0,0,0,0,0,127,127,127,0,126
Jaipur,0,0,0,0,0,0,0,0,0,0,22,23,1114,0,20
Kochi,0,0,0,0,0,0,0,0,0,0,162,0,162,0,4
Kolkata,0,0,0,0,0,0,0,0,0,0,1,1,420,0,60
Mumbai,0,0,0,0,0,0,0,0,0,0,210,993,994,0,1234
Patna,0,0,0,0,0,0,0,0,0,0,172,173,172,0,399
Shillong,0,0,0,0,0,0,0,0,0,0,33,34,310,0,105
Talcher,0,0,0,0,0,0,0,0,0,0,241,758,925,0,227
Thiruvananthapuram,0,0,0,0,0,0,0,0,0,0,1112,1112,1112,0,60
Visakhapatnam,0,0,0,0,0,0,0,0,0,0,38,38,38,0,291

In [51]:
df['Date'] = pd.to_datetime(df['Date'])

df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day

In [52]:

df.groupby("City").apply(lambda a: a.isnull().sum())

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,year,month,day
City,,,,,,,,,,,,,,,,,,
Ahmedabad,0,0,0,0,0,0,0,0,0,0,483,483,484,0,675,0,0,0
Aizawl,0,0,0,0,0,0,0,0,0,0,15,15,113,0,2,0,0,0
Amaravati,0,0,0,0,0,0,0,0,0,0,75,75,269,0,110,0,0,0
Amritsar,0,0,0,0,0,0,0,0,0,0,195,212,213,0,95,0,0,0
Bengaluru,0,0,0,0,0,0,0,0,0,0,266,93,2009,0,99,0,0,0
Bhopal,0,0,0,0,0,0,0,0,0,0,289,289,289,0,11,0,0,0
Brajrajnagar,0,0,0,0,0,0,0,0,0,0,173,938,938,0,225,0,0,0
Chandigarh,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0
Chennai,0,0,0,0,0,0,0,0,0,0,285,253,2009,0,125,0,0,0
Coimbatore,0,0,0,0,0,0,0,0,0,0,3,3,386,0,42,0,0,0
Delhi,0,0,0,0,0,0,0,0,0,0,0,0,781,0,10,0,0,0
Ernakulam,0,0,0,0,0,0,0,0,0,0,4,4,4,0,9,0,0,0
Gurugram,0,0,0,0,0,0,0,0,0,0,442,610,1560,0,226,0,0,0
Guwahati,0,0,0,0,0,0,0,0,0,0,7,502,502,0,7,0,0,0
Hyderabad,0,0,0,0,0,0,0,0,0,0,127,127,127,0,126,0,0,0
Jaipur,0,0,0,0,0,0,0,0,0,0,22,23,1114,0,20,0,0,0
Kochi,0,0,0,0,0,0,0,0,0,0,162,0,162,0,4,0,0,0
Kolkata,0,0,0,0,0,0,0,0,0,0,1,1,420,0,60,0,0,0
Mumbai,0,0,0,0,0,0,0,0,0,0,210,993,994,0,1234,0,0,0
Patna,0,0,0,0,0,0,0,0,0,0,172,173,172,0,399,0,0,0
Shillong,0,0,0,0,0,0,0,0,0,0,33,34,310,0,105,0,0,0
Talcher,0,0,0,0,0,0,0,0,0,0,241,758,925,0,227,0,0,0
Thiruvananthapuram,0,0,0,0,0,0,0,0,0,0,1112,1112,1112,0,60,0,0,0
Visakhapatnam,0,0,0,0,0,0,0,0,0,0,38,38,38,0,291,0,0,0

In [53]:
le = LabelEncoder()
df['City'] = le.fit_transform(df['City'])

In [55]:
X = df[['PM2.5', 'PM10', 'NO', 'NO2', 'NOx',
        'NH3', 'CO', 'SO2', 'O3',
        'year', 'month', 'day']]
y = df['AQI']

In [56]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [57]:
rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

In [58]:
rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [59]:
y_pred = rf.predict(X_test)

In [60]:
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

MAE : 19.300779738190098
RMSE: 38.71530018129125
R2 Score: 0.9116268123099995

In [61]:
print("Train Score:", rf.score(X_train, y_train))
print("Test Score :", rf.score(X_test, y_test))

Train Score: 0.9849699669810041
Test Score : 0.9116268123099995

In [63]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

importance = importance.sort_values(by='Importance', ascending=True)

print(importance)

   Feature  Importance
10   month    0.005155
5      NH3    0.005845
9     year    0.007077
11     day    0.008400
4      NOx    0.011603
3      NO2    0.011934
7      SO2    0.013367
8       O3    0.015563
2       NO    0.049647
1     PM10    0.053728
0    PM2.5    0.351470
6       CO    0.466212

In [66]:
joblib.dump(rf,'aqi_randomforest.pkl')

['aqi_randomforest.pkl']